### ISSUE TITLE
Transltr.org is down

### ISSUE THREAD

**Issue by jyoonbcit** [RPG-Maker-Translator/RPG-Maker-Translator#2]
"System is closed due to lack of support. Sorry but I can no longer spend time and money on this service."
Nothing is translating anymore... any way to change from the online translator to an offline one?

**Comment by ET619** [comment]
Such a shame this program is godly, hopefully it can get the much deserved fix/update to a new translation API

**Comment by jyoonbcit** [comment]
Yeah, until this I had no way to translate RPG Maker games. The source code is free so I hope someone can pick it up or continue it.

**Comment by hildelopes** [comment]
Use Google Translation API
Will need API KEY
Edit auto_translate.rb

`require 'net/https'`

`		$lastTranslateTime = Time.now			
		uri = URI("https://translation.googleapis.com/language/translate/v2?key=YOUR_API_KEY")
		begin			
			   Net::HTTP.start(uri.host) do |http|
	           req = Net::HTTP::Post.new(uri,{'X-HTTP-Method-Override' => 'GET'})
			   params = {
			   'format' => 'text',
			   'source' => 'ja',
			   'target' => 'en',
			   'q' => block
			   }
			   req.set_form_data(params)
			   https = Net::HTTP.new(uri.host, uri.port)
			   https.use_ssl = true
			   https.verify_mode = OpenSSL::SSL::VERIFY_NONE
			   res = https.request req
			   tes = JSON.parse(res.body)
			   trans = 'x'
			   tes["data"]["translations"].each do |player|
			      trans = player['translatedText']
			   end  
			  #response = http.request req # Net::HTTPResponse object
			  #trans = JSON.parse(response.body)["translationText"]
			  if trans == nil `

**Comment by ET619** [comment]
Thanks for that @takuha but i have no idea what im doing. I tried editing with notepad++ and it looks like this (https://puu.sh/wCKwf/efe00ae7dd.png) minus my api key obviously. Think you can upload your auto_translate.rb minus the API key and i can fill mine in instead?

**Comment by hildelopes** [comment]
yes, np @ET619 
LINK: [https://drive.google.com/file/d/0B_Zh1M7c2iNJR3F5QTJxWk54MVE/view?usp=sharing](https://drive.google.com/file/d/0B_Zh1M7c2iNJR3F5QTJxWk54MVE/view?usp=sharing)

**Comment by ET619** [comment]
@takuha tried it out just now and it works perfectly, Thanks so much for your fix!

**Comment by KleinHacks** [comment]
how exactly do i set this up, what api do I add where, is it possible to just get the file completed so i can just execute it?

**Comment by ET619** [comment]
1. Download the program normally from the github
2. go to https://console.cloud.google.com register and create a project, activate the google translate API and get a key (follow this guide: https://atrilsolutions.zendesk.com/hc/en-us/articles/205540421-How-to-obtain-a-Google-Translate-API-key)
3. Download Takuha's "auto_translate.rb" file
4. replace the original "auto_translate.rb" with the new one
5. open up the new "auto_translate.rb" file with notepad++ (https://notepad-plus-plus.org/download/v7.4.2.html)
6. ctrl+F and search googleapi
7. replace the "YOUR_API_KEY part of the URL with the API key you obtained through google.
8. the program should now work the same before just using google translate as the source instead of Transltr.org
(google API costs money based on how much you use it so youre going to need your own API key we wont give away ours, but the free trial lasts for one year or $300 which is more than enough for many translations.)

**Comment by KleinHacks** [comment]
okay thank you a lot this has really helped

**Comment by KleinHacks** [comment]
set it up and it seems to be working great now, thanks for the help

**Comment by jyoonbcit** [comment]
Thanks for the fix @takuha !
Would you happen to know any way to use a fully free online translator / offline translator rather than Google translate though?

**Comment by hildelopes** [comment]
I found a free API https://tech.yandex.com/translate/, but need to register to get KEY.

Link for auto_translate.rb [https://drive.google.com/file/d/0B_Zh1M7c2iNJazhONUF3SzJ0TGc/view?usp=sharing](https://drive.google.com/file/d/0B_Zh1M7c2iNJazhONUF3SzJ0TGc/view?usp=sharing)

replace the 'key' => 'YOUR_API_KEY',

**Comment by jyoonbcit** [comment]
Trying it out... it seems that most of the text does not get translated?

**Comment by ET619** [comment]
thats normal, some text is saved in a way that cannot get recognized by the scripts and it only works for certain RPG maker versions and also doesnt work for some developers depending on how they make the game. You can read more on that in the description for the program.

**Comment by breno987** [comment]
The Microsoft Azure Translation Service (https://azure.microsoft.com/en-us/services/cognitive-services/translator-text-api/) gives 2,000,000 characters for free every month (So they say at least).
If you can find the time do you think you could make a auto_translate.rb version for that?

**Comment by vicktorhu** [comment]
@takuha google doesn't give free accesss to the API anymore. There's other method like this: https://ctrlq.org/code/19909-google-translate-api. Do you mind updating your code?

Thanks!

**Comment by Tranquwil** [comment]
@Victh I took a crack at it.

Updated instructions:
1. Download the program normally from the github
2. go to https://www.google.com/script/start/ and press start scripting, copy [this code](https://gist.github.com/Tranquwil/34d76317febc96a1c1e228e2521e209c#file-translation_script-js) into it
3. click publish then deploy as web app, give the script whatever name and description you want, set "Execute the app as:" to me and "Who has access to the app:" to anyone, even anonymous then deploy
4. authorize the script then copy the "Current web app URL"
5. download my [auto_translate.rb](https://gist.github.com/Tranquwil/34d76317febc96a1c1e228e2521e209c#file-auto_translate-rb) file
6. replace the original "auto_translate.rb" with the new one
7. open up the new "auto_translate.rb" file with notepad++ (https://notepad-plus-plus.org/download/)
8. ctrl+F and search YOUR_WEB_APP_HERE
9. replace YOUR_WEB_APP_HERE with the link you copied to the web app
10. done

I used option 2 for the script but I don't understand the differences between them well and both seem to work. If anybody wants to switch just uncomment line 23, comment out 27-32 and publish as a new project version. After that if you want to swap again you can just set it to whichever version while publishing without needing to change the script.

**Comment by vicktorhu** [comment]
@Tranquwil I got an error on step 3 when I'm deploying the app.
`Missing ; before statement. (line 2, file "Code") ` on my Code.gs.

Also, should I left the `function myFunction() {}` or should I delete it? Sorry for the noobish question.

**Comment by Tranquwil** [comment]
@Victh Best to delete everything it starts you with. I think that error is just from me forgetting to add in some missing semicolons after copying the code. Should be fixed now if you copy the script again.
After the changes, if you already published, you will need to publish again and set "Project version:" to new.

**Comment by vicktorhu** [comment]
@Tranquwil The web app is running, but the RPG Maker Translator app keeps crashing. Is it working correctly on your end?

My exception stack, if you have an idea:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at WindowsFormsApplication1.RPGTranslator.translateButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Tranquwil** [comment]
@Victh Everything is working on my end. Things I would try:

- make sure you have all the dependencies, you might be missing ruby ([windows](https://rubyinstaller.org/), [other](https://www.ruby-lang.org/en/documentation/installation/))
- run as administrator
- turn off firewall
- in the folder shift right click and select open command window here then type
 `ruby auto_translate.rb "[PATH_TO_GAME_TO_TRANSLATE]"`
- using one of the previous auto_translate.rb files
- clean install from the start

**Comment by vicktorhu** [comment]
@Tranquwil Ah I forgot to install ruby on my current machine. Thanks! Seems working. Is there any chance that we could get banned for too much requests?

**Comment by Tranquwil** [comment]
@Victh No idea. Based on https://ctrlq.org/code/19909-google-translate-api I don't think so but if something like that does happen you can try switching to option 1 in the script.

**Comment by vicktorhu** [comment]
@Tranquwil the translation script is working great. However mine crashes at reconverting translated JSON files to rvdata. Tried on CircleKame's Parallel Fantasy 0. Currently trying some other games.

Did you managed to fully translate yours? What game have you tried?

Edit: made a new issue to keep the discussion clean.

**Comment by Swonyz** [comment]
Hi guys , recently i saw the update made by Tranquwil and i wanted to give it a try. I made everything work and i translated everything. But there is a thing that keeps me unable to play, when i launch the game , it says : 
///// Automatic generation of weapon description / 100////// "no method error" //////// undefined method 'name' for nil:NILClass                                                    ( those //// are japanese kanjis )

![rxdata actors]
(https://user-images.githubusercontent.com/34742007/34255611-c4f7b1ac-e651-11e7-859a-3b8bd4a4c307.jpg)

![json actors]
(https://user-images.githubusercontent.com/34742007/34255607-bde0e79e-e651-11e7-9661-f2982d359ecf.jpg)

Then i tried to replace the translation made in Json but there is much more text in RXdata than Json so i don't know what im supposed to do

**Comment by xerance** [comment]
@Tranquwil

Cant seem to find the option for anonymous for the app anymore, did they remove it?
  
getting: Translation API failed for [セリハ] with message: Web app doesn't allow anonymous access

**Comment by Tranquwil** [comment]
@xeratzy I'm guessing your problem is that "Execute the app as:" is set to "User accessing the web app". It will only give the option to allow anonymous in the drop down below that one when "Me (your email)" is selected.

**Comment by vicktorhu** [comment]
@Swonyz can you try to validate your JSON here: https://jsonlint.com/ ?

**Comment by Rocker-Fox** [comment]
Hey, i copied all the files and urls as directed and i keep getting this error 

Translation API failed for [*text*] with message: SSL_connect returned=1 errno=0 state=error: certificate verify failed

I tried 2 fresh re-installs and i keep getting this error. Any way to fix this or alternatively is there a full zip with a working folder that i can get?

**Comment by xerance** [comment]
@Tranquwil
sorry for late reply, had a lot of work going on.
https://puu.sh/z1JFK/995d832b20.png
this is the options i can select, where/how do i change it to anonymous?

**Comment by Tranquwil** [comment]
@xeratzy The fix for your problem is in step 3 of my instructions and my last post:

> set "Execute the app as:" to me and "Who has access to the app:" to anyone, even anonymous

This is referring to 2 of the drop down menus that can be seen in your picture.

**Comment by ChromJed** [comment]
@Tranquwil Hey! Currently trying to use your method to get the program working, and all seems to be fine except that the program can't connect to the API correctly. I've made sure to double and triple check all the steps you gave, and tried the other solutions as well. This is the error I'm getting.
http://prntscr.com/i3c6m6
Do you know of any possible solutions?

**Comment by DorianWang** [comment]
@ChromJed In case you haven't fixed it yet updating ruby should help. OpenSSL doesn't seem to exist in ruby 2.2.

**Comment by ChromJed** [comment]
@dustan1 Sorry for the late response. But now I am getting this error.
http://prntscr.com/ihn7s4
Any idea on how to fix it? Judging by the looks, it looks like a character is wrong or something has changed? But I don't know exactly what.

**Comment by cloverpi** [comment]
@Tranquwil

Thank you very much for doing this.  Absolutely awesome to be using google translate instead of these odd options like yandex which provided terrible translations (no disrespect intended for the author of that patch).

**Comment by hyou-f** [comment]
I followed this guide and made it kinda work using Ruby 2.4.3-1. It began translating and worked there for some hours and then it said the operation finished (the loading bar was not full) and the game is still in japanese. Anybody know what could it be or how can i make it work?

**Comment by cloverpi** [comment]
@hyou-f 
That should probably be a new issue...

Your game will be wherever the export directory was+the folder name of the original directory.  So if your game was located at c:\Civilization6 and your export directory was set to c:\export, your translated game will be in c:\export\Civilization6

If you chose the same directory as the export (which is a bad idea), say you chose c:\civilization6 and an export of c:\civilization6, your translated game will be in the folder:  c:\civilization6\civilization6

**Comment by hyou-f** [comment]
@ronkkrop I chose diferent folders for the output and the game itself but that's the issue i'm having. In the output folder there are translations and everything but the game is still in japanese...

**Comment by cloverpi** [comment]
@hyou-f from my experience, the titlescreen is still in japanese, as well as some of the menu entries.  Scripts that contain text (which often happen at the start of a game) are still in Japanese, unless you select the option to translate scripts as well, which I don't because it can break the game. 

In your export folder, you should see a log file called "RPG Maker Auto-translate.log".  open it in notepad++ and scroll through it.  Are there translations in there?  when you get to the end, did it mention any errors?

**Comment by hyou-f** [comment]
@ronkkrop I tried again and it started to translate from where the bar left the first time. Then it stopped a few times more but I kept insisting on it and eventually the bar filled, when I opened it it was translated so I just had to be persistant. Sorry for the bother! (and thanks for the help)

**Comment by Arkus86** [comment]
@Tranquwil Thanks for the support, I would just like to mention this:
 with option 2 I was getting an error about doGet function not found, but after switching to option 1 the program seems to be working just fine.

**Comment by Traveler121** [comment]
@Arkus86  Can you help me, I get the Output directory not found. I think the problem is in the google script that I need to make. Can you give me the right route? like option 1 or 2? how do I make that right?

**Comment by Traveler121** [comment]
@Tranquwil  Can you help me, I get the Output directory not found. I think the problem is in the google script that I need to make. Can you give me the right route? like option 1 or 2? how do I make that right?

**Comment by Tranquwil** [comment]
@Traveler1234 From the readme:

> Troubleshooting
I hit translate and it gave no output and stopped immediately, wtf?
The most common reason this would happen is if your output directory does not exist.
The other common reason for this both the source and the destination directory cannot contain Japanese anywhere in the path. Ruby in Windows cannot seem to handle the copy when Japanese chars exist in the path.

If you didn't notice the settings button at the top left of the GUI that is where you change the output dir.

**Comment by Traveler121** [comment]
@Tranquwil  I did all that and it  still won't work.   

And how do I choose option 1 or 2 with the code? because I got this problem when I changed the code in the auto_translate.rb with putting the link in it.

**Comment by Tranquwil** [comment]
@Traveler1234 You should be able to avoid this error by using the command window as it will create a new output dir by itself. In the tool's root directory shift right click and select open command window here then type
`ruby auto_translate.rb "[PATH_TO_GAME_TO_TRANSLATE]"`
replacing [PATH_TO_GAME_TO_TRANSLATE] with your own path
example: `ruby auto_translate.rb "c:\games\RJ123456"`

This error shouldn't have anything to do with my changes or the google script but that said here is how to switch options. Option 2 is the default and Option 1 looks like this
```ruby
  /* Option 1 */
  
  var translatedText = LanguageApp.translate(sourceText, sourceLang, targetLang);
  
  /* Option 2 */  
  
  /* var url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=" 
            + sourceLang + "&tl=" + targetLang + "&dt=t&q=" + encodeURI(sourceText);
  
  var result = JSON.parse(UrlFetchApp.fetch(url).getContentText());
  
  var translatedText = result[0][0][0]; */
```

**Comment by Traveler121** [comment]
@Tranquwil   You should be able to avoid this error by using the command window as it will create a new output dir by itself. In the tool's root directory shift right click and select open command window here then type
ruby auto_translate.rb "[PATH_TO_GAME_TO_TRANSLATE]"
ex: ruby auto_translate.rb "c:\games\RJ123456"

When I do that I get this(see pic)
https://user-images.githubusercontent.com/38857588/39444719-f63dc10c-4cb8-11e8-986d-f061b485fdac.jpg

Sry for being a pain in the ass :(   

Could you maybe send your files if that would work?

**Comment by Tranquwil** [comment]
@Traveler1234  You are supposed to replace [PATH_TO_GAME_TO_TRANSLATE] with the path you want, `ruby auto_translate.rb "c:\games\RJ123456"` being an example of what it should look like after doing so. Edited my last comment to be more clear.

**Comment by Traveler121** [comment]
@Tranquwil  So I did that and now I get this 
https://user-images.githubusercontent.com/38857588/39445350-141f8a64-4cbb-11e8-92b4-01c09f33334c.jpg 

Before that, I changed the code with the option 1 and 2. Then I checked it with Web-app testing with new code and I get this. 
https://user-images.githubusercontent.com/38857588/39445471-6d39ace2-4cbb-11e8-9b4d-d5b91729d556.jpg (was a bad pic)

And this is how my code looks like with google)

https://user-images.githubusercontent.com/38857588/39445575-c31a0daa-4cbb-11e8-85bd-bf57974bc923.jpg

**Comment by Tranquwil** [comment]
@Traveler1234 The line of code it is complaining about is the one where you need to replace "YOUR_WEB_APP_HERE" with the link to your script. It should look something like this:
`uri = URI("https://script.google.com/macros/s/***********************/exec")`

**Comment by Traveler121** [comment]
@Tranquwil  I have done that. But I have found the problem.  "https://script.google.com/macros/s/***********************/exec"  I forgot to put the  >"<  between https://script.google.com/macros/s/***********************/exec -_-

now it doesn;t crash at all.

**Comment by Traveler121** [comment]
@Tranquwil  I posted this solution on other issue: #8 (comment) (closed). Work great for me.

Yeah I just solved my similar error. I know you have closed the issue, but I have some quick way to resolve it.

Step 1Check what *.rvdata files are missing from your Data folder
step2 Find the bad *.JSON file on your DataExtracted folder. The program generate the rvdata files in iteration, so it shouldn't be too hard to guess.
step3 Copy paste the content of our bad JSON file to https://jsonlint.com/ to easily find the error.
Step4 Recompile your scripts. I use this command for VX Ace games ruby "[PATH TO RPGM TRANSLATOR]/RPG-Maker-Translator-master/3rdParty/rmxp_translator/rmvxace_translator.rb" --translate="[PATH TO GAME]/DataExtracted/*.rvdata2" --dest="[PATH TO GAME]/Data"
Step5 Repeat to first step if you get any error, until you have all the *.rvdata files on DataExtracted inside the Data folder.
So far worked great, though I can't fix a bad 'script.rvdata' file yet. I just copy pasted the untranslated 'script.rvdata' from DataExtracted folder.

Sry to bother you again. but could you explain step 4 for me, how do I do that command? 

I finaly got it to work but the bloody common event's won't get translated except the names of the charachters. 60% off the game I want translated uses common events ;(

**Comment by Tranquwil** [comment]
@Traveler1234 Open a command window in the root directory same as last time then use
```
ruby "3rdParty\rmxp_translator\rmvxace_translator.rb" --translate="[PATH TO GAME]\DataExtracted\.rvdata2" --dest="[PATH TO GAME]\Data"
```
replacing both [PATH TO GAME]s with your own path
example: 
```
ruby "3rdParty\rmxp_translator\rmvxace_translator.rb" --translate="c:\games\RJ123456\DataExtracted\.rvdata2" --dest="c:\games\RJ123456\Data"
```
I haven't tried this fix myself but I hope it works for you.

**Comment by J4zzN4zz** [comment]
@Tranquwil 

I keep getting this "Unexpected token" error that @ChromJed is suffering from. I updated Ruby to 2.5, and even tried 'ruby auto_translate.rb "[PATH_TO_GAME_TO_TRANSLATE]" '.

Note: My system locale is Japanese, so in directory paths, I have yen signs instead of "\".

Do you have any idea what's going on?

The error :

Translation API failed for [繧・◆縺犠 with message: 751: unexpected token at '<!DOCTYPE html><html><head><link rel="shortcut icon" href="//ssl.gstatic.com/docs/script/images/favicon.ico"><title>ﾘｮﾘｷﾘ｣</title><style type="text/css">body {background-color: #fff; margin: 0; padding: 0;}.errorMessage {font-family: Arial,sans-serif; font-size: 12pt; font-weight: bold; line-height: 150%; padding-top: 25px;}</style></head><body style="margin:20px"><div><img alt="Google Apps Script" src="//ssl.gstatic.com/docs/script/images/logo.png"></div><div style="text-align:center;font-family:monospace;margin:50px auto 0;max-width:600px">ﾘｪﾘｹﾘｰﾘｱ ﾘｧﾙ・ｹﾘｫﾙ畏ｱ ﾘｹﾙ・・ﾘｯﾘｧﾙ・ｩ ﾘｧﾙ・・ｵ ﾘｧﾙ・ｨﾘｱﾙ・ｬﾙ・ doGet</div></body></html>'

Translation API failed for [繧・◆縺犠 with message: 751: unexpected token at '<!DOCTYPE html><html><head><link rel="shortcut icon" href="//ssl.gstatic.com/docs/script/images/favicon.ico"><title>ﾘｮﾘｷﾘ｣</title><style type="text/css">body {background-color: #fff; margin: 0; padding: 0;}.errorMessage {font-family: Arial,sans-serif; font-size: 12pt; font-weight: bold; line-height: 150%; padding-top: 25px;}</style></head><body style="margin:20px"><div><img alt="Google Apps Script" src="//ssl.gstatic.com/docs/script/images/logo.png"></div><div style="text-align:center;font-family:monospace;margin:50px auto 0;max-width:600px">ﾘｪﾘｹﾘｰﾘｱ ﾘｧﾙ・ｹﾘｫﾙ畏ｱ ﾘｹﾙ・・ﾘｯﾘｧﾙ・ｩ ﾘｧﾙ・・ｵ ﾘｧﾙ・ｨﾘｱﾙ・ｬﾙ・ doGet</div></body></html>'

**Comment by DigimonLee** [comment]
It worked fine for me, thx for this. 'll study japanese some day, but for now i'm really grateful that u did this.

**Comment by J4zzN4zz** [comment]
@DigimonLee Can you walk me through what you did ? Was your system locale Japanese ?

**Comment by DigimonLee** [comment]
Well, i just perfomed like Tranqwil said, and yes i use AppLocate, but i dnt know if this will help you. Give it a try. (Anyway i've been using the Japanese, Chinese and Korean installed on my machine.)

**Comment by YukiSakuma** [comment]
Is there anyway to just use the https://translate.google.com/ instead of that translate API?

**Comment by Jwguy** [comment]
Doesn't currently work. Provides the following error several times: "Translation API failed for [斧技ダウン] with message: Failed to open TCP connection to transltr.org:80 (getaddrinfo: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server. )"

I also attempted to follow along with the Google Script instructions provided on December 5th, but the file provided is rejected as missing semicolons on line 1.

**Comment by YukiSakuma** [comment]
@Jwguy the Dec 5 instructions worked for me 
but anyway I tried translating an RPG and translation didn't turn out well (e.g it was translated as "Powered by Discuz", "AlsoHousehold appliances Let's do it-"  and some unrelated garbled translation maybe google translator's fault or RPG Maker Translator messed up the original text to be translated)

**Comment by Jwguy** [comment]
Ah, you know what, I think I got mixed up somewhere down the line. Let me try this again.

**Comment by coolyves** [comment]
Hello Everyone
My translator work really well with the Google API but I did last night a really big mistake. I shutdown my Computer without closing the translator first and now my "translation_en.json" is corrupt. Has someone a "translation_en.json" for me? I don't want to start at the beginning.
Greetings

**Comment by RenegadeBeam** [comment]
@coolyves 
https://mega.nz/#!qdEV2ahR!nfi7EYaNBHzn5_1GlNzyhG9dxTMnHwTrWhA9IQ-ACJ8

**Comment by coolyves** [comment]
@RenegadeBeam 
Thank you very much. It have more chached than i had before.
Have a nice Day

**Comment by RenegadeBeam** [comment]
@coolyves 
That sounds like I'm the pervert with all the translated games

**Comment by GreyQual** [comment]
First of all thanks for your time and effort on this @Tranquwil. I have a question that I think you already responded to, but when I tried copying your autotranslate.rb code to deploy as a web app, I get an error, that says 'Missing ; before statement. (line 1, file "auto_translate")'. I saw that you had mentioned that you had edited the code later so do you know what the problem is? Thanks!

Edit: As a total noob, I realize I probably copied the wrong script.

**Comment by GreyQual** [comment]
It's working fine now and translating, but it gets stuck towards the end. Something about moving data file game.rgss3a to backup. Then it says 'processed 564281 lines in 145 seconds' and then just gets stuck there, making me abort the process. Any leads would be appreciated, thanks!

**Comment by RenegadeBeam** [comment]
@GreyQual  Could you give us the exact error message?

**Comment by GreyQual** [comment]
Pretty much exactly this. I've tried it multiple times, but it stops pretty much at the same place each time.
![error](https://user-images.githubusercontent.com/40537375/42068489-1ef0dd2a-7b01-11e8-8b86-36507b795f65.JPG)

**Comment by RenegadeBeam** [comment]
@GreyQual Your path under "Game Directory" looks a bit strange.
Can you change the path so that the input path and the output path are different?

**Comment by GreyQual** [comment]
So the Input and Output path are different I made sure of that. I changed it again to be sure, but it still doesn't work. For reference, when it does complete translation, does the abort change into something else? Or is there a message saying that the translation was a success? I've noticed that even though my translation always gets stuck there, when I open the output folder, I see the game and when I open it, I see partially translated stuff.
